"""add category and level to course

Revision ID: 6d74b7b17cbf
Revises: 276fa0c26c2e
Create Date: 2025-05-21 16:35:13.983685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d74b7b17cbf'
down_revision = '276fa0c26c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_lessons', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('bio')
        batch_op.drop_column('role')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('last_accessed')
        batch_op.drop_column('completed_lessons')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('level')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
